name: "Test"

on: [push, pull_request]

jobs:

  server:
    uses: petrjasek/superdesk/.github/workflows/server.yml@chore-reusable-github-workflows

  client:
    uses: petrjasek/superdesk/.github/workflows/client.yml@chore-reusable-github-workflows

  docker:
    uses: petrjasek/superdesk/.github/workflows/docker.yml@chore-reusable-github-workflows
