name: "Test"

on: [push, pull_request]

jobs:

  server:
    uses: superdesk/superdesk/.github/workflows/server.yml@develop

  client:
    uses: superdesk/superdesk/.github/workflows/client.yml@develop

  docker:
    uses: superdesk/superdesk/.github/workflows/docker.yml@develop
